[package]
name = "rovo"
version = "0.1.0"
authors = ["Darshan Kathiriya <darshankathiriya121@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.13.0"
num = "0.3"
num-traits = "0.2"
dyn-clone = "1.0.2"
reduce = "0.1"